# Generated by Django 4.0 on 2022-01-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
