# Generated by Django 4.0 on 2022-01-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
