# Generated by Django 4.0 on 2022-01-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0002_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='girth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
