# Generated by Django 4.0 on 2022-01-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0003_horse_girth_horse_height_horse_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='horse',
            name='training',
        ),
        migrations.AlterField(
            model_name='image',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='horse',
            name='training',
            field=models.ManyToManyField(to='horse.Training'),
        ),
    ]
