# Generated by Django 4.0 on 2022-01-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0004_training_remove_horse_training_alter_image_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
