# Generated by Django 4.0.1 on 2022-01-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0005_training_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horse',
            old_name='age',
            new_name='year_foaled',
        ),
    ]
