# Generated by Django 4.0.1 on 2022-02-06 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0006_rename_age_horse_year_foaled'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
