# Generated by Django 4.0.1 on 2022-02-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0008_auto_20220206_0501'),
    ]

    operations = [
    ]
