# Generated by Django 4.0.1 on 2022-02-06 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0009_auto_20220206_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='id',
        ),
        migrations.AlterField(
            model_name='horse',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
