# Generated by Django 4.0.1 on 2022-02-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0010_remove_horse_id_alter_horse_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horse',
            old_name='uuid',
            new_name='id',
        ),
    ]
