# Generated by Django 4.0.1 on 2022-02-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0011_rename_uuid_horse_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horse',
            old_name='id',
            new_name='uuid',
        ),
    ]
