# Generated by Django 4.0.1 on 2022-02-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0012_rename_id_horse_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horse',
            old_name='uuid',
            new_name='id',
        ),
    ]
