# Generated by Django 4.0.1 on 2022-02-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0013_rename_uuid_horse_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='horse',
        ),
    ]
