# Generated by Django 4.0.1 on 2022-02-06 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0014_remove_image_horse'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='horse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horse.horse'),
        ),
    ]
