# Generated by Django 4.0.1 on 2022-02-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0015_image_horse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='training',
        ),
    ]
