# Generated by Django 4.0.1 on 2022-02-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0016_remove_horse_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='training',
            field=models.ManyToManyField(null=True, to='horse.Training'),
        ),
    ]
