# Generated by Django 4.0.1 on 2022-02-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0020_alter_note_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_created',
            new_name='date',
        ),
    ]
