# Generated by Django 4.0.1 on 2022-02-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0022_medical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='exam_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='vet',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
