# Generated by Django 4.0.1 on 2022-02-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0023_alter_medical_date_alter_medical_exam_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='name',
            field=models.CharField(default='No Name Entered', max_length=200),
            preserve_default=False,
        ),
    ]
