# Generated by Django 4.0.1 on 2022-02-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0026_alter_image_private_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical',
            name='weight',
        ),
        migrations.AddField(
            model_name='medical',
            name='black_tape',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='girth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='red_tape',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
