# Generated by Django 4.0.1 on 2022-02-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0027_remove_medical_weight_medical_black_tape_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medical',
            options={'get_latest_by': 'date'},
        ),
        migrations.RemoveField(
            model_name='horse',
            name='girth',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='height',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='length',
        ),
    ]
