# Generated by Django 4.0.3 on 2022-06-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0028_alter_medical_options_remove_horse_girth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='brand',
            field=models.CharField(default=12345678, max_length=8),
            preserve_default=False,
        ),
    ]
